import Head from "next/head";
import SideNavbar from "../../components/SideNavbar";
import { useDispatch, useSelector } from 'react-redux';
import { useRouter } from "next/router";
import { DropDown, InputBox, SimpleBackdrop, DropDownData } from "../../components/commonComponent";
import { useEffect } from "react";
import { addOrUpdate, populateData } from "../../utils/constants";

export default function Home() {
  const dispatch = useDispatch()
  const router = useRouter()
  const { updatePacket, str, gotu } = useSelector((state) => state)

  useEffect(() => {
    populateData()
  }, [router.query])

  useEffect(() => {
    if(gotu){
      dispatch({type: "GOTU", payload: false})
      router.push("/orders")      
    }    
  }, [gotu]);
  return (
    <div className="bg-blue-800">
      <SimpleBackdrop />
      <Head>
        <title>Responsive Side-Navbar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <SideNavbar />
      <div style={{ padding: "24px 20px 31px 267px", background: "white" }}>
        <div style={{ display: "flex" }}>
          <h1 style={{ fontWeight: "bolder", fontSize: "x-large" }}>{str}</h1>
        </div>
        {
          <div style={{ marginTop: "30px", border: "2.5px solid #737889", padding: "30px", borderRadius: "10px" }}>
            <div className="row" style={{ marginBottom: "20px" }}>
              <div className="col-md-4">
                <InputBox value={updatePacket.vehicleName} label={"Vehicle Name"} placeholder={"vehicleName"} />
              </div>
              <div className="col-md-4">
                <InputBox value={updatePacket.vehicleImage} label={"Vehicle Image"} placeholder={"vehicleImage"} />
              </div>
              <div className="col-md-4">
                <DropDown label={"Location"} />
              </div>
            </div>
            <div className="row" style={{ marginBottom: "20px" }}>
              <div className="col-md-4">
                <DropDown label={"Sub Location"} />
              </div>
              <div className="col-md-4">
                <InputBox value={updatePacket.userName} label={"User Name"} placeholder={"userName"} />
              </div>
              <div className="col-md-4">
                <InputBox value={updatePacket.email} label={"Email"} placeholder={"email"} />
              </div>
            </div>
            <div className="row" style={{ marginBottom: "20px" }}>
              <div className="col-md-4">
                <InputBox value={updatePacket.contact} label={"Contact"} placeholder={"contact"} />
              </div>
              <div className="col-md-4">
                <InputBox readOnly={true} value={updatePacket.vehicleNumber} label={"Vehicle Number"} placeholder={"vehicleNumber"} />
              </div>
              <div className="col-md-4">
                <InputBox value={updatePacket.startDate} label={"Start Date"} placeholder={"startDate"} />
              </div>
            </div>
            <div className="row" style={{ marginBottom: "20px" }}>
              <div className="col-md-4">
                <InputBox value={updatePacket.startTime} label={"Start Time"} placeholder={"startTime"} />
              </div>
              <div className="col-md-4">
                <InputBox value={updatePacket.endDate} label={"End Date"} placeholder={"endDate"} />
              </div>
              <div className="col-md-4">
                <InputBox value={updatePacket.endTime} label={"End Time"} placeholder={"endTime"} />
              </div>
            </div>
            <div className="row" style={{ marginBottom: "20px" }}>
              <div className="col-md-4">
                <InputBox value={updatePacket.paymentStatus} label={"Payment Status"} placeholder={"paymentStatus"} />
              </div>
              <div className="col-md-4">
                <InputBox value={updatePacket.paymentMethod} label={"Payment Method"} placeholder={"paymentMethod"} />
              </div>
              <div className="col-md-4">
                <InputBox value={updatePacket.submittedDocument} label={"Submitted Document"} placeholder={"submittedDocument"} />
              </div>
            </div>
            <button onClick={() => {
              addOrUpdate("/createOrder")
            }} style={{ marginTop: "20px", width: "50%", padding: "12px", background: "black", color: "white", borderRadius: "12px" }}>{str}</button>
          </div>
        }

      </div>
    </div>
  );
}
