import Head from "next/head";
import SideNavbar from "../../components/SideNavbar";
import DisplayTable from "../../components/table/orderTable";
import { SimpleBackdrop } from "../../components/commonComponent";
import { IoIosAddCircle } from "react-icons/io";
import Link from "next/link";
import { useEffect } from "react";
import { setReduxData } from "../../utils/constants";
import { useSelector } from "react-redux";

export default function Home() {
  const {apiData} = useSelector(state => state)
  useEffect(() => {
    (async () => {
      if(apiData && !apiData.length){
        await setReduxData()
      }            
    })()
  }, [])
  return (
    <div className="bg-blue-800">
      <SimpleBackdrop />
      <Head>
        <title>Responsive Side-Navbar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <SideNavbar />
      <div style={{ padding: "24px 20px 31px 267px", background: "white" }}>
        <div style={{ display: "flex" }}>
          <h1 style={{ fontWeight: "bolder", fontSize: "x-large" }}>ORDER LIST</h1>
          <Link href="/addEditUser" style={{ marginLeft: "auto" }}>
            <button style={{ marginLeft: "auto", padding: "12px", background: "black", color: "white", borderRadius: "12px", display: "flex" }}><span style={{ marginRight: "5px" }}>ADD ORDER </span> <IoIosAddCircle style={{ marginTop: "5px", marginRight: "5px" }} /></button>
          </Link>
        </div>
        <DisplayTable />
      </div>
    </div>
  );
}
