import Head from "next/head";
import SideNavbar from "../../components/SideNavbar";
import { useDispatch, useSelector } from 'react-redux';
import { useRouter } from "next/router";
import { DropDown, InputBox, SimpleBackdrop } from "../../components/commonComponent";
import { useEffect, useState } from "react";
import { getApi, postApi } from "../api/response";
import { IoIosAddCircle } from "react-icons/io";

export default function Home() {
  const dispatch = useDispatch()
  const router = useRouter()
  const { totalData } = useSelector((state) => state)
  const [packet, setPacket] = useState("")

  useEffect(() => {
    if (router.query) {
      const query = router.query._id
      const find = totalData.find(o => o._id == query)
      if (find) {
        setPacket(find)
      }
    }
  }, [router.query])
  return (
    <div className="bg-blue-800">
      <SimpleBackdrop />
      <Head>
        <title>Responsive Side-Navbar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <SideNavbar />
      <div style={{ padding: "24px 20px 31px 267px", background: "white" }}>
        <div style={{ display: "flex" }}>
          <h1 style={{ fontWeight: "bolder", fontSize: "x-large" }}>ADD OR UPDATE VEHICLE</h1>
        </div>
        {
          <div style={{ marginTop: "30px", border: "2.5px solid #737889", padding: "30px", borderRadius: "10px" }}>
            <div className="row" style={{ marginBottom: "20px" }}>
              <div className="col-md-4">
                <InputBox value={packet.name} label={"Name"} placeholder={"name"} />
              </div>
              <div className="col-md-4">
                <InputBox value={packet.url} label={"Url"} placeholder={"url"} />
              </div>
              <div className="col-md-4">
                <DropDown setPacket={setPacket} packet={packet} label={"Location"} location={packet.location} />
              </div>
            </div>
            <div className="row" style={{ marginBottom: "20px" }}>
              <div className="col-md-4">
                <DropDown setPacket={setPacket} location={packet.location} packet={packet} label={"Sub Location"} pickupLocation={packet.pickupLocation} />
              </div>
              <div className="col-md-4">
                <InputBox value={packet.pricePerday} label={"Price Per Day"} placeholder={"pricePerDay"} />
              </div>
              <div className="col-md-4">
                <InputBox value={packet.distanceLimit} label={"Distance Limit"} placeholder={"distanceLimit"} />
              </div>
            </div>
            <div className="row" style={{ marginBottom: "20px" }}>
              <div className="col-md-4">
                <InputBox value={packet.accessChargePerKm} label={"Access Charge Per Km"} placeholder={"accessChargePerKm"} />
              </div>
              <div className="col-md-4">
                <InputBox value={packet.vehicleNumber} label={"Vehicle Number"} placeholder={"vehicleNumber"} />
              </div>
              <div className="col-md-4">
                <InputBox value={packet.transmissionType} label={"Transmission Type"} placeholder={"transmissionType"} />
              </div>
            </div>
            <div className="row" style={{ marginBottom: "20px" }}>
              <div className="col-md-4">
                <InputBox value={packet.brand} label={"Brand"} placeholder={"brand"} />
              </div>
              <div className="col-md-4">
                <InputBox value={packet.bookingAmount} label={"Booking Amount"} placeholder={"bookingAmount"} />
              </div>
              <div className="col-md-4">

              </div>
            </div>
            <button style={{ marginTop: "20px", width: "50%", padding: "12px", background: "black", color: "white", borderRadius: "12px" }}>{packet ? "Update" : "Add"} Vehicle</button>
          </div>
        }

      </div>
    </div>
  );
}
