import Head from "next/head";
import SideNavbar from "../components/SideNavbar";
import { useDispatch, useSelector } from 'react-redux';
import { useRouter } from "next/router";
import DisplayTable from "../components/table/vehicleTable";
import { CardComponent, SimpleBackdrop } from "../components/commonComponent";
import { useEffect } from "react";
import { getApi, postApi } from "./api/response";
import { IoIosAddCircle } from "react-icons/io";
import { Link } from "@mui/material";
import { setReduxData } from "../utils/constants";
import Image from "next/image";

export default function Home() {
  const { apiData, vehicleCount } = useSelector(state => state)
  useEffect(() => {
    (async () => {
      if (apiData && !apiData.length) {
        await setReduxData()
      }
    })()
  }, [])
  useEffect(() => {
    console.log(apiData)
  }, [apiData])
  return (
    <div className="bg-blue-800">
      <SimpleBackdrop />
      <Head>
        <title>Responsive Side-Navbar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <SideNavbar />
      <div style={{ padding: "108px 20px 31px 267px", background: "white"}}>
        <div className="row" style={{marginBottom: "83px"}}>
          <div className="col-md-4">
            <CardComponent name={"VEHICLES"}/>
          </div>
          <div className="col-md-4">
            <CardComponent name={"USERS"} />
          </div>
          <div className="col-md-4">
            <CardComponent name={"LOCATIONS"} />
          </div>
        </div>  
        <div className="row" style={{marginBottom: "83px"}}>
          <div className="col-md-4">
            <CardComponent name={"ORDERS"} />
          </div>
          {/* <div className="col-md-4">
            <CardComponent name={"USERS"} count={200} />
          </div>
          <div className="col-md-4">
            <CardComponent name={"LOCATIONS"} count={200} />
          </div> */}
        </div>        
      </div>
    </div>
  );
}
